# A proposal for the new input config file taken by Shaka-Streamer

# It has multiperiod_inputs & single_inputs entries so they match the 
# class fields in the InputConfig class.
# However, that's not so user friendly, and since the 'input_list' & 'inputs'
# as keys define whether this input is of type [period concat] or [single good ole input],
# this can be handled inside Shaka-Streamer, meaning that the user won't have to write 
# multiperiod_inputs or single_inputs, and they will be injected from within Shaka-Streamer
# so that it follow the InputConfig structure and easier to be dealt with.

# check input_multiperiod_multiinput_simple_config.yaml


multiperiod_inputs:

  - inputs_list:

    - inputs:
      - name: blah.mp4
        media_type: video
      
      - name: blah.mp4
        media_type: audio
        language: ar

    - inputs:
      - name: file.mkv
        media_type: video

  - inputs_list: # this list will be concatenated as periods as a final output
    - inputs: # list of inputs (one video stream & multiple audio/text streams)
    - inputs: # list of inputs (one video stream & multiple audio/text streams)
    - inputs: # list of inputs (one video stream & multiple audio/text streams)

single_inputs:

  - inputs: # this single inputs serves as the whole input_config file before
    - name: blahblah.mp4
      media_type: video # single video stream per 'inputs'
    
    - name: blahb.mp4
      media_type: audio ################
      language: de                    ###
                                      ###### multiple audio streams
    - name: blahbbutinarabic.mp4      ###
      media_type: audio ################
      language: ar

    - name: blah.mkv
      media_type: text
      language: de
  
  - inputs:
    - name: anotherblah.mp4
      media_type: video
